### ISSUE TITLE
Issue with react-storybook

### ISSUE THREAD

**Issue by swistaczek** [CodingZeal/phoenix-react-apollo-demo#4]
Hi,
While exploring some new stuff implemented by You I encounter problem with launching ```react-storybook```.  I tried expanding file paths but it does not solve issue so there is some other issue which is not so clear for me, right now I try to catch up this new approach to front end development ;).

Stacktrace:
```js
# npm run storybook
ERROR in ./client/stories/index.js
Module not found: Error: Cannot resolve module 'modules/todo' in /Users/ernest/Projects/elixir/phoenix-react-apollo-demo/client/stories
 @ ./client/stories/index.js 13:12-35

ERROR in ./client/stories/index.js
Module not found: Error: Cannot resolve module 'styles/commons.scss' in /Users/ernest/Projects/elixir/phoenix-react-apollo-demo/client/stories
 @ ./client/stories/index.js 15:0-30

ERROR in ./client/stories/index.js
Module not found: Error: Cannot resolve module 'styles/theme' in /Users/ernest/Projects/elixir/phoenix-react-apollo-demo/client/stories
 @ ./client/stories/index.js 17:13-36
```

**Comment by lexun** [comment]
Hi @swistaczek, it looks like I forgot to update the storybook config when I did this: https://github.com/CodingZeal/phoenix-react-apollo-demo/commit/bd4a8a57f59b9631577ed85c89f8d301ebf1e285

The [@zeal/react-scripts](https://www.npmjs.com/package/@zeal/react-scripts) package hosts the client webpack config, which I updated here: https://github.com/CodingZeal/create-react-app/commit/fe312119078d29a36ea4eee1a91d442c19d55de4.

React storybook has its own webpack config though, which also needs to be told where the resolve root is. I'll have a fix up in a few minutes.
